### ISSUE TITLE
Fix Key Grabber Tool Sprites

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#102]
The sprites should be in there already, just not using the correct sprite

**Comment by VtorHdev** [comment]
Tried to find the missing assets in hd/global/ui/items/misc, but I could only see the Gem Grabber assets.

In items.json I found this:
` { "tkg": { "asset": "body_part/player_ear" } },
{ "hkg": { "asset": "body_part/player_ear" } },
{ "dkg": { "asset": "body_part/player_ear" } },`

Pushed in 2021, as part of '1.12.1 hotfix'. Never modified. I have tried to find a video on YouTube where these objects appear, but I have not seen them anywhere.

**Comment by Delegus** [comment]
Fixed in pull #374
