### ISSUE TITLE
Clickable Area of Cube Incorrect

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#105]
![image](https://github.com/user-attachments/assets/3b7b62ba-e56b-4628-a27e-8bd7d9673dd2)

The right side after the transmute button should not click through and send the move command like it is now

**Comment by CollinHerber** [comment]
Both stash and inventory

**Comment by Orin55** [comment]
![CUBE](https://github.com/user-attachments/assets/e0f6a102-aaab-4ee2-8809-b9b894357b79)
![STASH](https://github.com/user-attachments/assets/58c3bbdf-d8fb-44e8-909d-94a7795d97dd)

These areas outside of the red box to be precise.
These "clickable" areas in the stash and cube screens are misaligned with the new UI.
If you click outside of the red marked area, it gives a walk command to your character, closing the stash screen.
