### ISSUE TITLE
New endgame Sets for each Class

### ISSUE THREAD

**Issue by Harald92** [D2R-Reimagined/d2r-reimagined-mod#112]
At the moment I am working on new endgame sets for each class an wanted to get some feedback or if people are interrested at all.

I like sets but there are no sets which have real endgame potential, which I want to change. Each set consits of 9 parts and gets a big boost to its strength when all 9 parts are worn. I compare all stats of items from the standard meta builds to implement and improve on them for those sets, of course I will consider the new items and runewords provided inside D2R reimagined.

### Amazon
- Javelin _(Lightning/Poison)_
- Spear _(Physical/Lightning)_
- Bow _(Multishot/Strafe/Frost/Fire)

### Asassin
- Elemental Claw _(Pheonix Strike/Claws of thunder)_
- Traps _(Possibilities for lightning and fire)_
- Kick _(Dragon Tail/Dragon Talon)_

### Berserk
- Berserk _(Berserk)_
- Throw _(Double Throw)_
- Combat _(Frenzy/Whirlwind)_

### Druid
- Shape Shift _(Fury/Fire Claw)_
- Elemental _(Fire/Physical/Cold)_
- Summoning _(Pets)_

### Necromancer
- Poison_ (Poison Nova)_
- Summoning _(Pets)_
- Bone _(Bone Spear)_

### Paladin
- Holy _(Hammer/FoH)_
- Zeal _(Zeal)_
- Smite _(Smite)_

### Sorceress
- Fire _(Fire specialized)_
- Cold _(Cold specialized)_
- Lightning _(Lightning specialized)_

**Comment by Maowiwowi** [comment]
I agree that sets with endgame potential are cool, however, I think the overall power should be something like 85% of what perfect rolled runewords/rares that have been corrupted are. I think a good place for set items in the end game is essentially the entry point to true endgame. They can allow a class to beat all content though struggle at points.

I also think that this mod has a shit-ton of sets and uniques that should be looked over and adjusted for balance or for being too similar to another.

**Comment by Harald92** [comment]
> I agree that sets with endgame potential are cool, however, I think the overall power should be something like 85% of what perfect rolled runewords/rares that have been corrupted are. I think a good place for set items in the end game is essentially the entry point to true endgame. They can allow a class to beat all content though struggle at points.
> 
> I also think that this mod has a shit-ton of sets and uniques that should be looked over and adjusted for balance or for being too similar to another.

For my taste there should be both, endgame sets which are as viable as a mix of unique, set and runewords. Since D2RR provides one with so many and easier to get runes it feels kind of easy to create very powerfull items and the looting part gets cut short because all you need is any base, socket punch it and create the meta runewords.

Since the sets are only at full power when you wear all 9 set items, and since those set items consist only of elite base items, it will take some time to find all items of one set which should be rewarded with a powerfull set. On top of that is that I plan to let the part only drop from Lvl 87+ mobs which needs one to adventure the highest level zones or terror zones for that loot.

A 9 piece set does not allow for any customisation which for some is the main point to creating builds, but nobody has to use those sets and I am to not make them to overpowered so all other item combinations would be weaker.

**Comment by Harald92** [comment]
Got enough feedback, will create the sets and then talk about it again
