### ISSUE TITLE
Metamorphosis Tooltip is bugged

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#119]
![image](https://github.com/user-attachments/assets/49a3fbc3-c771-4da8-90cd-db8e5a7f39a3)

**Comment by Doxorn** [comment]
Fix is in the #215 pull request skilldesc.txt
![Metamorphosis fixed](https://github.com/user-attachments/assets/1faf3dff-c38f-46da-b7d5-5aba7c3b6411)
