### ISSUE TITLE
Reroll amulet/ring recipes are flipped

### ISSUE THREAD

**Issue by Nick-Conrad** [D2R-Reimagined/d2r-reimagined-mod#137]
REROLL MAGIC RING - 3 Magic Rings = Magic Amulet
REROLl MAGIC AMULET - 3 Magic Amulets = Magic Ring

lines 15-16 of cubemain.txt

1 Magic Amulet

**Comment by Harald92** [comment]
Solved with  qol: cubemain.txt Update 2.0 #178
