### ISSUE TITLE
Skill points unable to be allocated with controller

### ISSUE THREAD

**Issue by dstaley** [D2R-Reimagined/d2r-reimagined-mod#15]
I am unable to allocate skill points with a controller using the latest version (v1.14.3). Using the mouse works though!

**Comment by CollinHerber** [comment]
> I am unable to allocate skill points with a controller using the latest version (v1.14.3). Using the mouse works though!

I know this is SUPER late but this next release of D2R Reimagined will have an emphasis on controller support. Sorry for the EXTREMELY long delay on this.

**Comment by CollinHerber** [comment]
This has been resolved in the 1.16.0 with a completely redesigned controller UI. Enjoy!
