### ISSUE TITLE
Add loot beam to Orb on Conversion

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#156]
With how rare this item is, I think it's worth adding a loot beam to it.
Will need to create a json file if not already exists. There are examples in the project already

**Comment by victoria-riley-barnett** [comment]
Is this still relevant or can we close? I see 
<img width="722" alt="Screenshot 2024-10-22 at 10 39 26 AM" src="https://github.com/user-attachments/assets/352ce614-1253-4759-bbc3-0316aff926cb">

**Comment by victoria-riley-barnett** [comment]
But havent dropped a conversion in 1.21

**Comment by CollinHerber** [comment]
This is completed. Just not closed.
