### ISSUE TITLE
Too much MF from 1 Source overflows

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#160]
Similar issue happens with Deadly Treasures barb passive skill.
![image](https://github.com/user-attachments/assets/8db8b720-202f-47d4-bf41-19ee100061be)
![image](https://github.com/user-attachments/assets/6bc99e13-c1a8-4ac6-a1d5-3301e6889857)
![image](https://github.com/user-attachments/assets/a5624fa8-6182-4dba-8ba9-8c81a5513e65)

Weirdly enough, it looks like even though it is signed, there is some funky behind the scenes stuff to prevent negative MF.

**Comment by wjakiela** [comment]
I confirm. I have the same in Deadly Treasures case. If I add point to Deadly Treasures and overload some mf level it doesn't add more mf. Despite that I can add mf from other sources.

**Comment by Harald92** [comment]
Did you test if making 2 MF prop would work?

**Comment by Bakelt** [comment]
For DT, this could be a possible solution. Split it into 2 and just display the sum of the two.
For items, too much of a pain and Collin has mentioned a lot of the items from Talonrage used something else to increase the caps. We may not even want that powercreep and the integer limit is just a bug acting as a balancing tool.

**Comment by Harald92** [comment]
Not more of a pain as reodering the cubemain file. Powercreep is an important bullet to dodge, but balancing stuff is never easy.

**Comment by Harald92** [comment]
The adding item stat system via cube has the same problem, opened another Issue for it _**Stat overflow for Item upgrading via Cube #179**_
