### ISSUE TITLE
monstats.txt and skills.txt crash the game

### ISSUE THREAD

**Issue by maistoast** [D2R-Reimagined/d2r-reimagined-mod#17]
Hello, I know it's not supported but I'd like to use your mod in linux with wine. These 2 files crash my game:
mods/merged/merged.mpq/data/global/excel/monstats.txt
mods/merged/merged.mpq/data/global/excel/skills.txt

If I remove these files the game starts and I can play with no problems. Can you please tell me what I am missing without these files?

Thanks for this great mod!

**Comment by CollinHerber** [comment]
These files are required in order for the mod to function. Sorry.
