### ISSUE TITLE
Reminder: Remove Magic Arrows and Magic Bolts from Akara

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#171]
These bolts aren't the same as charsi bolts and won't work with crafts

**Comment by victoria-riley-barnett** [comment]
taking a look at this

**Comment by victoria-riley-barnett** [comment]
Line 226, 227 in misc.txt. Fara can spawn these as well, thought its not clear to me their chance to actually roll as magic (and thus distinguish themselves) works if that the intent? Itemtype is z01 (arrows) or z02 in other references (item-name, items.txt).

**Comment by Bakelt** [comment]
It looks like they are the base type (z01) used for the crafted arrows. So you can essentially buy the crafted arrow with no affixes but these aren't a valid input for the recipe itself.

Should just need to remove the values in the [npc]min/max/magicmin/magicmax for Akara and Charsi as well as PermStoreItem (column FH).

**Comment by victoria-riley-barnett** [comment]
yep, done

**Comment by victoria-riley-barnett** [comment]
& tested
