### ISSUE TITLE
Improvement: Revamp uniques.txt, setitems.txt and sets.txt to reference skill names

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#175]
There are a lot of items that reference their hit-skill, oskill, +skill, and att-skill (might have missed some) by their skill's ID # and not their skill's skilldesc attribute.

This means that inserting a skill or reorganizing these, which will almost certainly happen in 2.0 when we expand the class skills with buffer, will cause a LOT of uniques to have the wrong skill.

Someone with better scripting skills should tackle this.

**Comment by Doxorn** [comment]
In case anyone wants to do it. This will help. All skills and their ID's are here in 2 column format for scripts
[skillid_map.txt](https://github.com/user-attachments/files/17355828/skillid_map.txt)

**Comment by Harald92** [comment]
For "skill-rand" using the skill names will not work I guess, I did not test it but in properties the values are definde by skill ID.

**Comment by Harald92** [comment]
> In case anyone wants to do it. This will help. All skills and their ID's are here in 2 column format for scripts [skillid_map.txt](https://github.com/user-attachments/files/17355828/skillid_map.txt)

the skill 66 which is Amplify Damage is setup wrong i think, it is called "Amplify DAmazonge".

**Comment by Harald92** [comment]
> There are a lot of items that reference their hit-skill, oskill, +skill, and att-skill (might have missed some) by their skill's ID # and not their skill's skilldesc attribute.
> 
> This means that inserting a skill or reorganizing these, which will almost certainly happen in 2.0 when we expand the class skills with buffer, will cause a LOT of uniques to have the wrong skill.
> 
> Someone with better scripting skills should tackle this.

I have done my best with the help of ChatGPT  Improvement revamp item skills #185

**Comment by Doxorn** [comment]
> > In case anyone wants to do it. This will help. All skills and their ID's are here in 2 column format for scripts [skillid_map.txt](https://github.com/user-attachments/files/17355828/skillid_map.txt)
> 
> the skill 66 which is Amplify Damage is setup wrong i think, it is called "Amplify DAmazonge".

Yes, good find. It was an error from where I copied the original. I was tired already, haven't noticed it. Updated the .txt file

**Comment by Harald92** [comment]
PR #185 created for this Issue
