### ISSUE TITLE
Missing Strings

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#177]
Missing strings for:
Serpent Lord
Blanched Death
Rat Lord's Curse
Medusa's Gaze(?) - Someone had two but only 1 was missing a name and had a different sprite.

**Comment by Harald92** [comment]
Are those missing in item-names.json?

**Comment by victoria-riley-barnett** [comment]
- Rat lords seems to just be named wrong? <img width="262" alt="Screenshot 2024-10-18 at 12 40 00 PM" src="https://github.com/user-attachments/assets/ee5b65fa-7abb-4955-b9c4-acf38909dc76">
- Blanched Death is not in item-names
- Serpent Lord, Medusa's are in item-names.json.
