### ISSUE TITLE
Uniform file with ingame names

### ISSUE THREAD

**Issue by Harald92** [D2R-Reimagined/d2r-reimagined-mod#188]
There are multiple uniques which have different names in the files compared to the ingame name. For this issue to be solved each item need's to be looked at.

> The "Chaoskiller" item ingame have the "Chaos Flight" name since it wasn't updated in the **..\data\local\lng\strings\item-names.json** 
> ![item-names.json](https://github.com/user-attachments/assets/deec515a-b2ee-4bdd-b4eb-0c4ed0a4059e)
> ![chaoskiller_ingame](https://github.com/user-attachments/assets/27cbb1c9-8c39-48dd-89ba-5703f800ae66)
> 
> _Originally posted by @Doxorn in https://github.com/D2R-Reimagined/d2r-reimagined-mod/issues/185#issuecomment-2413570392_
>

**Comment by Doxorn** [comment]
I am not sure which one is intended, but I made a python script that compared all "Key" and "enUS" entries in **item-names.json**, ignoring cases where the Key length is only 3 characters long (obviously og blizzard codes) and letter case differences.
The results are in this text file. If you scroll down (a lot) I have separated the Blizzard and Reimagined names (I guess we don't want to modify Blizzard Keys and Names but I left them there just in case).
It is only about 60 entries for Reimagined, give or take.
[item-names_mismatches.txt](https://github.com/user-attachments/files/17392661/item-names_mismatches.txt)

**Comment by Harald92** [comment]
Nice, I will check it out. Something like `Mismatch: Key="Godstrike Arch" enUS="Goldstrike Arch"` which is vanilla I think would be subject to change too. I would not change the ID, I would change the name to be safe and only if it is appropiate.

**Comment by Doxorn** [comment]
You are safe to change the Key just make sure to change their "index" name in their respective .txt files as well to not break the reference

**Comment by Harald92** [comment]
Updated the PR **_Improvement: revamp item skills #185_** to solve this issue,
