### ISSUE TITLE
Hydra delays and max pets do not match Blizzard 

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#190]
Do we want to incorporate this change?

Currently we have a max off 99 (33) and delays of 20
Blizzard changed to a max of 18 (6) and delays of 0

**Comment by Bakelt** [comment]
Gonna say no after a quick test. It looks like our implementation is probably fine and may even be preferred.
![image](https://github.com/user-attachments/assets/93121ab7-9e78-4b39-9751-d42301fbfecb)

**Comment by Bakelt** [comment]
I believe this change is going into v1.21 with the other missing 2.4 changes but we could always revert it with your other changes in 2.0

**Comment by Harald92** [comment]
No problem, the changes I think of for skills are nothing more than ideas jet. I first have to finish other stuff.
