### ISSUE TITLE
Char's Annulus of Obscurity (Ring) doesn't reward the correct amount of + Sanctuary skill

### ISSUE THREAD

**Issue by RegularAlicorn** [D2R-Reimagined/d2r-reimagined-mod#193]
Wearing the Ring 
**Char's Annulus of Obscurity**
From the Set
**Narrow Path Between Light and Darkness**

With +13/+12 Sanctuary awards just +3 to Sanctuary (instead of +13/+12 stated on the item)
![image](https://github.com/user-attachments/assets/6db26774-195e-44a8-b594-75cd24e765ea)

![image](https://github.com/user-attachments/assets/1a62516e-e8ce-46ea-a2b5-3283e179ad97)

**Comment by Harald92** [comment]
I assume you are wearing that ring as a paladin? Sadly it is hardcoded into the game for the prop _**skill**_ classes which already have that skill only gain a max of +3 to that skill. We can only assume why but I would guess it is to make items with skills from other classes usable for a class without that skill and not making the class which already has said skill to overpowered.
