### ISSUE TITLE
Improvement: Uniform runeword names

### ISSUE THREAD

**Issue by Harald92** [D2R-Reimagined/d2r-reimagined-mod#206]
Uniform runeword names inside runes.txt with item-runes.json.

The question here is if it would be a problem to change the name of the runewords inside runes.txt to the actual runeword name instead of "Runeword1". Does someone know if that would cause problems?

**Comment by Bakelt** [comment]
It looks like the only reference to "Runeword1" and the rest is in item-runes.json

If the runes.txt AND the key in item-runes.json are both updated then there would be no issue

**Comment by Harald92** [comment]
I looked over it too and came to the same conclusion.

**Comment by Bakelt** [comment]
Have we already made a similar update for Sets? I know a few people have complained that they struggle to look up sets on the website since it also imports the "Set35" stuff instead of a name.

**Comment by Harald92** [comment]
I have made an update for set names some time ago. In that change I changed the names of sets and set items according to their name because they were just called set1, set2 and so on.

It was PR  #161
