### ISSUE TITLE
Upgrade basetype of set weapon can brick usability

### ISSUE THREAD

**Issue by victoria-riley-barnett** [D2R-Reimagined/d2r-reimagined-mod#207]
![image](https://github.com/user-attachments/assets/842bbeb8-2848-4475-a856-17f09e39bc96)

1h sword bricked in both known cases (my own, and pictured from Tetra)

**Comment by Harald92** [comment]
Bricked means that the weapon was not equitable after being upgraded to a higher quality even when the requirements to wear it are met.

**Comment by victoria-riley-barnett** [comment]
I've been trying to reproduce it to confirm the patch, but no luck bugging one so far. I think I was wearing pieces of the set like Tetra is when it happened to me, is there some bizarro world where that matters?

**Comment by victoria-riley-barnett** [comment]
ah, they're not bricked - I think they're just (elite base level req) + an additional 7 levels, which only shows when either:
- you cubed with no set pieces equipped?
- you put on the piece of gear

Cubed with set item on:
![2sword](https://github.com/user-attachments/assets/68677a9d-7c19-4541-ad8c-6bb7602fd6ec)
![1sword](https://github.com/user-attachments/assets/f4aef585-f5a2-4350-8a61-42b777959792)

Cubed with no other set pieces equiped:
![4swrod](https://github.com/user-attachments/assets/ea2d1e19-1677-41eb-9b26-b31addcfa06a)
![3sword](https://github.com/user-attachments/assets/5f1510e3-90c0-427d-90d3-322cc2ed4977)

**Comment by victoria-riley-barnett** [comment]
![image](https://github.com/user-attachments/assets/67bf3d82-2cbc-4653-a13c-79838e94e0c9)
![image](https://github.com/user-attachments/assets/20a240df-450b-4294-b635-9be646e06a2d)

This is happening with uniques as well, it appears all basetype swaps handle their level req just fine without adding levels via cubestats
