### ISSUE TITLE
uniques.json / sets.json were not updated with the uniqueitems.txt and setitems.txt

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#236]
e.g. Bonesob was renamed Bonesnap to match its displayed name

uniques.json still is looking for the "bonesnap" keyword to display the "bonesob" graphic
![image](https://github.com/user-attachments/assets/a7f88a83-fd2c-4359-8d90-2f289eafe0f4)

should be changed to
![image](https://github.com/user-attachments/assets/80f86411-86ff-4c90-92f8-bffa0e999c66)

Would not recommend changing the "hammer/bonesob" as this is likely the image to be used.

I've verified this will fix the individual item but someone needs to do a recrawl through ALL uniques and sets that were changed.
![image](https://github.com/user-attachments/assets/3e46fb38-77e6-4138-a2a3-d065f6828287)
![image](https://github.com/user-attachments/assets/ad5b51f7-3a70-4344-a49f-8b6b0cc55db8)

**Comment by Harald92** [comment]
I will work on that tomorrow

**Comment by Harald92** [comment]
#246 should solve this.

**Comment by Harald92** [comment]
https://github.com/D2R-Reimagined/d2r-reimagined-mod/pull/246 should solve this.
