### ISSUE TITLE
Rare Ring & Rare Amulet Reroll Recipe wrong in Menu

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#241]
Inside the menu for crafting recipies it says 3 amulets = 1 amulet, it's supposed to be 3 amulets = 1 ring.

**Comment by victoria-riley-barnett** [comment]
<img width="527" alt="Screenshot 2024-10-22 at 11 33 22 AM" src="https://github.com/user-attachments/assets/99cc580e-c9bb-4bc3-8838-59b58a725950">
is the inverse (3 ring rare = 1 rare amulet) also supposed to be true?

**Comment by CollinHerber** [comment]
Pretty sure the 3 ring = 1 amulet recipe is vanilla

**Comment by victoria-riley-barnett** [comment]
https://diablo2.io/recipes/

I only see magic here.

**Comment by victoria-riley-barnett** [comment]
Anyways, I can adjust cubemain for rings to match as well as the menus
