### ISSUE TITLE
Adding Max All res to shields

### ISSUE THREAD

**Issue by Sharac85** [D2R-Reimagined/d2r-reimagined-mod#267]
Adding additional +to max all res on shied did not work

**Comment by CollinHerber** [comment]
Are you speaking about 
![image](https://github.com/user-attachments/assets/60886a3e-00ee-449e-85f7-8af0d9023b47)


?

**Comment by Sharac85** [comment]
<img width="863" alt="image" src="https://github.com/user-attachments/assets/1128c793-4708-436e-931c-618feab5e706">
 This recipe from the wiki did not work for me

**Comment by Vaiyne** [comment]
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/186473655/382486868-1128c793-4708-436e-931c-618feab5e706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1ODc3NDcsIm5iZiI6MTczMDU4NzQ0NywicGF0aCI6Ii8xODY0NzM2NTUvMzgyNDg2ODY4LTExMjhjNzkzLTQ3MDgtNDM2ZS05MzFjLTYxOGZlYWI1ZTcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQyMjQ0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjYyMDdiYmJjOGMyMjlkODQzZTBjZjc5YTJmNjVlY2Q0NjVhOGJjMzJhZGM1YTg2ZGQ5ZTBmNDgwYmZkMjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7wfodT87TPaWSScpByj-zpiJMa22xMkPtfxGU-4A3QU"> This recipe from the wiki did not work for me

Following cubemain.txt reciple is: ADD ITEM STAT - Shield & Gul & Vex & Ohm & Lo = Shield & Res-all max +5
runes: r25 r26	r27	r28

wiki is incorrect

**Comment by Vingelis** [comment]
This has been corrected on the wiki
