### ISSUE TITLE
Fist of heavens (FoH) casting delay

### ISSUE THREAD

**Issue by csisy** [D2R-Reimagined/d2r-reimagined-mod#283]
The skill tooltip says that the casting delay is 0.4 sec but it feels way more, closer to 1 or 1.4 sec.

Just compared to the original live d2r version and the casting delay is higher than it should.

**Comment by csisy** [comment]
I just found the appropriate section. In the `global\excel\skills.txt` file the FoH has 25 delay which is 1 seconds. Changed it to 10 and it matches the original d2r.

**Comment by CollinHerber** [comment]
I think we kept it at 25 due to the other changes of it damaging everything.
I don't think it needs a buff at this time

**Comment by csisy** [comment]
I see. Is it possible to update the tooltip then? Thank you for the response.
