### ISSUE TITLE
Crushing blow not working

### ISSUE THREAD

**Issue by sammynammari** [D2R-Reimagined/d2r-reimagined-mod#285]
I've noticed that crushing blow doesn't seem to be applied. For example, using a character with > 50% crushing blow, and when smiting ubers, it's very clear that no crushing blow is being applied.

**Comment by VtorHdev** [comment]
I tested this with a non-smiter character to see the difference better, and I do see it apply without any problem. With a 15% chance of CB, most of my hits do little to no damage, until two or three Crushing Blows come out that are very noticeable.

https://github.com/user-attachments/assets/74b37766-d3cf-4356-9952-2f306e4e7ddf
