### ISSUE TITLE
Skulls dont drop

### ISSUE THREAD

**Issue by Vaiyne** [D2R-Reimagined/d2r-reimagined-mod#292]
After finishing normal difficulty, jumped to nightmare.
Playing From level 28 to level 56 at nightmare (act 1- 5) did not  dropped single skull.

Also lost my Gem Bag during game crash, and cannot recreate one without getting single skull.

Edit: Skulls drop again normally at Hell difficulty

**Comment by VtorHdev** [comment]
I was testing this in Nightmare doing Cows and I could see at least one Flawless Skull in my second game.
![image](https://github.com/user-attachments/assets/ef2e79eb-3717-4b1d-bf5d-6401932f8544)
