### ISSUE TITLE
Suggestion Skill change Holy Bolt

### ISSUE THREAD

**Issue by neodata83** [D2R-Reimagined/d2r-reimagined-mod#293]
Hello

found this Mod via youtube and Once again im hooked to D2 :D 
I have a change in mind that another MOD had done to the Skill. At every 15 Point in the Skill you got an extra Bolt. Maxed out at 4 i belive. 
At the moment i have to little time to do it myself. If anybody have time to do it feel free otherwise i look into it when i have more time.

**Comment by VtorHdev** [comment]
IMO Holy Bolt is one of the most broken skills in the mod (without items). If we add 3 more bolts to the skill, that would be 2x to 4x more broken at basis, and you would not even need any items to beat the game (in fact, I would bet that right now, if you play safe, you can finish Hell completely naked, only weapon/shield and charms).
