### ISSUE TITLE
Re-enable several disabled superunique & champion modifiers

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#296]
In the mod several modifiers like the enchanted modifiers that can appear randomly on superuniques and rare packs have been disabled. Re-enable these. 
This should allow for immunities to pop up every now and then for a bit more dynamic experience and also reduce the times you see amp damage as this is a common complaint.

**Comment by Bakelt** [comment]
I finally won't have to redo this change every update: #298
