### ISSUE TITLE
orbs, gem bag, unique large charms keep disappearing

### ISSUE THREAD

**Issue by markusobi** [D2R-Reimagined/d2r-reimagined-mod#306]
After entering the game with a char, I noticed holes in my inventory and stash.
I've experienced this three or more times already.
The holes in my inventory are two slots high and are in the lower area of my inventory where I keep all my charms.
I can't find the unique (D2RR specific) large charm that I definitely found.
Also ALL conversion/corruption/socket orbs and gem bag are gone. All were stored in personal chest.
Made me quit the game for now - but the mod is great!

I upgraded to 1.21.1 and hoped that it would help - but problem happened again.
Versions used:
D2R Reimagined - 1.20.2-503-1-20-2-1728517461
D2R Reimagined - 1.21.1-503-1-21-1-1729768978

**Comment by Bakelt** [comment]
Most common cause for this is overloading the cube storage which causes the file to become too large to load and things get truncated. Would recommend not using cube as additional storage and to not leave items in it that take up a lot of storage like the gem bag.
