### ISSUE TITLE
Set Orbs

### ISSUE THREAD

**Issue by Delegus** [D2R-Reimagined/d2r-reimagined-mod#337]
We have socketing orbs, corruption orbs and conversion orbs. 

Currently there is no orb to make an item into a set.

Proposed: Cube conversion alone = Set orb. Cube set orb alone = Conversion orb.

Idea: Since we added recycling into rare jewels from unique/set jewelry, rare jewel*9 + 1 unique or +1 set = Orb of that type.

Make conversion set orbs work the same way as the finalized idea in issue 336 based on either A: required level B: required level +8 or C: random chance based on rarity.

Currently rare jewels are just a stopgap between magic and rare aside from the few people that use them to socket set items they luck into. This will make it easier to get set items you wish, give rare jewels more of a purpose, and take away from unique item jewel chase using recycle recipe.

**Comment by Vingelis** [comment]
Have addressed the initial proposed idea and left the other ideas concerning recycling to be raised in a new issue.
