### ISSUE TITLE
 dmg value in dexterity text field in mercenary menu when in controller UI

### ISSUE THREAD

**Issue by JHenneberg** [D2R-Reimagined/d2r-reimagined-mod#339]
1.21.1
The dmg numbers of the mercenary are at the dexterity position. This is only happening when game is controlled by a controller and not a keyboard.
![image](https://github.com/user-attachments/assets/d1ba9a09-920f-4878-9d61-5a00c74f9f66)

Could you activate the labes and maybe add labels for the different release versions. I guess this would be also beneficial for you?

**Comment by Delegus** [comment]
Reproduced and investigating the issue; Labels and stuff is out of my wheelhouse.

**Comment by Delegus** [comment]
![image](https://github.com/user-attachments/assets/c39b02b5-c758-4eec-b244-1de205adec5f)
![image](https://github.com/user-attachments/assets/b3ab0681-5442-4662-a864-501de75f972d)

Worked it out;
