### ISSUE TITLE
Terror Key GFX

### ISSUE THREAD

**Issue by Vingelis** [D2R-Reimagined/d2r-reimagined-mod#359]
Problem: While subtle changes have been made to the keys to distinguish them, players want more visual fidelity.

Proposal: Update key sprites to have a slight colored border, either around the outside of the whole key, or just the negative spaces in the head

Outcome(s): Easier to distinguish keys at a glance, enhances the more subtle visual changes to the keys already introduced

**Comment by Delegus** [comment]
Related Issue #102 - I have also checked for these files and cannot find them; There are supposed to be unique sprites for each key and key grabber already, but they're not in the files on Nexus or Git.

**Comment by Delegus** [comment]
@CollinHerber
