### ISSUE TITLE
Add Synergies for orb so we can have a full frozen orb option

### ISSUE THREAD

**Issue by Nattyx1989** [D2R-Reimagined/d2r-reimagined-mod#364]
Please add atleast 1 more synergy for frozen orb, maybe frost nova? atm its just lackluster but is my fav skill in the game, thnx

**Comment by Delegus** [comment]
Pull #406 testing indicated more synergy makes FOrb OP in /players 8, resolving. We are looking at updating masteries and will also link this issue when that is settled.
