### ISSUE TITLE
Missing Strings post #372

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#373]
Compile any still missing strings here

![image](https://github.com/user-attachments/assets/13447a0b-805f-4801-9bc6-ca1a59417ad0)

**Comment by Bakelt** [comment]
> This is even after merging the updates I did in? Hrm.

It used to be Missing String of Missing String so at least one got covered. I'd wait a few days to see if we come across any more and then do another update

**Comment by Delegus** [comment]
Bone spear affix update was completed and so far there have been no additional reports of missing strings. Issue is being closed and can be revisited/reopened if needed.
