### ISSUE TITLE
ED/Min or Max Jewel Socket Bug

### ISSUE THREAD

**Issue by Vingelis** [D2R-Reimagined/d2r-reimagined-mod#375]
Common bug in D2R regarding socketing jewels with both ED and Min/Max Damage properties into a non-weapon item results in the item ignoring all ED enhancements.

We currently have a Star Facet Unique Jewel that has both both of these modifiers. We should rework it, or add a disclaimer somewhere that people shouldn't try to use these jewels in anything other than a weapon.

**Comment by Delegus** [comment]
Loads of unique and set items also have damage % and flat damage of one type or the other on them which may have been fixed in the original mods code but are not working properly here.
