### ISSUE TITLE
request: Eth / Socket separator.

### ISSUE THREAD

**Issue by Nyxet** [D2R-Reimagined/d2r-reimagined-mod#54]
Separate colors of Ethereal and Socketed items.
It's a simple edit in _profilehd.json
![image](https://github.com/user-attachments/assets/715fa4c4-982a-4ff5-b077-88fb9c1aa3f8)

Haven't used the pull request shit before or i'd have put it in myself.

**Comment by CollinHerber** [comment]
> Separate colors of Ethereal and Socketed items. It's a simple edit in _profilehd.json ![image](https://private-user-images.githubusercontent.com/129768887/371819348-715fa4c4-982a-4ff5-b077-88fb9c1aa3f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTU0NjIsIm5iZiI6MTcyNzYxNTE2MiwicGF0aCI6Ii8xMjk3Njg4ODcvMzcxODE5MzQ4LTcxNWZhNGM0LTk4MmEtNGZmNS1iMDc3LTg4ZmI5YzFhYTNmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMzA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWUwYTgyZDc1MjE0Y2VmZTZjOTgyZmU5MjJlOTJlMGI2ZDU0NTdiNTE1NjhiODFkNzgzY2I3N2E1ZjBlYzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F60B0y6OmucO7gtcm_LN_pwETkxAmLifdsnb-x5vhsM)
> 
> Haven't used the pull request shit before or i'd have put it in myself.

Is this something new? I looked into this in 2.3 days and it was not possible.

**Comment by CollinHerber** [comment]
Resolved in 1.18.0
