### ISSUE TITLE
Incorrect Patchnotes or file for "The Stone of Jordan" for 1.8.0

### ISSUE THREAD

**Issue by Harald92** [D2R-Reimagined/d2r-reimagined-mod#56]
The patchnotes for 1.8.0 on reddit say

- Increases Stone of Jordan Lightning Damage

but inside the "uniqueitems.txt" the only change made to "The Stone of Joraden" is 

- "mana% 25 25" to "mana% 25 50"

Is the change inside the file wrong or are the patchnotes wrong?

**Comment by CollinHerber** [comment]
This was resolved in 1.19.0
