### ISSUE TITLE
Gamepad access to H-Cube Listed as L: Missing String

### ISSUE THREAD

**Issue by evbo** [D2R-Reimagined/d2r-reimagined-mod#7]
Harmless little bug whereby for a gamepad the `L` hotkey from the inventory is listed as `Missing String` when really it should be something like "Open Cube".

Thanks for a ~great~ amazing mod!

**Comment by CollinHerber** [comment]
I know this is very late but this has been resolved in 7deb9035443a84275fbafa8da58142b906b7d3c7
