### ISSUE TITLE
book of identify doesn't cast from mercenary inventory with gamepad

### ISSUE THREAD

**Issue by evbo** [D2R-Reimagined/d2r-reimagined-mod#8]
A small bug: when viewing the mercenary inventory on a gamepad, holding down "A" on a tome doesn't cast the tome of identify. You can cast it however from the regular inventory, so no big deal.

**Comment by CollinHerber** [comment]
> I am unable to allocate skill points with a controller using the latest version (v1.14.3). Using the mouse works though!

I know this is SUPER late but this next release of D2R Reimagined will have an emphasis on controller support. Sorry for the EXTREMELY long delay on this.

**Comment by CollinHerber** [comment]
This was resolved with 1.16.0
