### ISSUE TITLE
missing files?

### ISSUE THREAD

**Issue by SaijC** [D2R-Reimagined/d2r-reimagined-mod#81]
Hello,

first off, LOVE the mod but i keep crashing every time i talk to Akora:

- running mod version 1.19.0
- I use PS4 controller
- play on a 34" ultra wide screen

10/5 09:20:54.928  [aio/4] [<>:0]: Failed to open file. Error (3): The system cannot find the path specified
10/5 09:20:54.928  [aio/4] [<>:0]: Encountered an unexpected result. Error (3): The system cannot find the path specified
10/5 09:20:54.928  [tact/4] [<>:0]: Failed to open the config file for reading.
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file death.d2s in container death
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file death.key in container death
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file death.map in container death
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file isa.d2s in container isa
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file isa.key in container isa
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file isa.map in container isa
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Saij.ctl in container Saij
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Saij.d2s in container Saij
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Saij.key in container Saij
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Saij.ma0 in container Saij
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Saij.map in container Saij
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Created save file Settings.json in container Settings
10/5 09:20:55.162  [SaveSystem/4] [<>:0]: Mounting death at c:/Users/FangC/Saved Games/Diablo II Resurrected/mods/Merged/ in mode 2
10/5 09:20:55.171  [SaveSystem/4] [<>:0]: Unmounting death
10/5 09:20:55.172  [SaveSystem/4] [<>:0]: Mounting Saij at c:/Users/FangC/Saved Games/Diablo II Resurrected/mods/Merged/ in mode 2
10/5 09:20:55.183  [SaveSystem/4] [<>:0]: Unmounting Saij
10/5 09:20:55.183  [SaveSystem/4] [<>:0]: Mounting Settings at c:/Users/FangC/Saved Games/Diablo II Resurrected/mods/Merged/ in mode 2
10/5 09:20:55.187  [SaveSystem/4] [<>:0]: Unmounting Settings
10/5 09:20:55.187  [SaveSystem/4] [<>:0]: Mounting isa at c:/Users/FangC/Saved Games/Diablo II Resurrected/mods/Merged/ in mode 2
10/5 09:20:55.192  [SaveSystem/4] [<>:0]: Unmounting isa
10/5 09:20:57.721  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Help
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteSentList
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteReceivedList
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: List
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Add
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Remove
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteAccept
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteReject
10/5 09:20:57.722  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteSentRevoke
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnoreNotifications
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnoreWhisper
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignoreWhisper
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePrivate
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePrivate
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePublic
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePublic
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignoreNotifications
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignoreWhisper
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnoreWhisper
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePrivate
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePrivate
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePublic
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePublic
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: NotifyToggle
10/5 09:20:57.723  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnoreWhisper
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignoreWhisper
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePrivate
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePrivate
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: IgnorePublic
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UnignorePublic
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Dnd
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Away
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Online
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Offline
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Dnd
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Away
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Online
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Offline
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: WhoAmI
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: WhoIs
10/5 09:20:57.724  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Time
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Ladder
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: UberDiablo
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: DesecratedOnline
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: DesecratedOffline
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Desecrated
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: SendMessage
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: SendMessage
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Ignore
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Unignore
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: InviteReceivedList
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: List
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Join
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Leave
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Private
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Invite
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Kick
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Designate
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Resign
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Accept
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Reject
10/5 09:20:57.725  [CommandDefinition/4] [<>:0]: Could not find ExecuteCommandCallback: Who
10/5 09:21:01.305  [BGSEnvironmentMap/4] [<>:0]: Environment Status: PROD - us.actual.battle.net - Release
10/5 09:21:03.242  [D2BackendServices/4] [<>:0]: D2BackendServices: error: 7 Error Source: 0 Error Value: 7 String: Cannot Connect to Server
10/5 09:21:07.775  [UI/4] [<>:0]: Unknown profile value in JSON file ($SkillHotkeyTextAltStyle)
10/5 09:21:07.811  [UI/4] [<>:0]: Unknown profile value in JSON file ($SkillHotkeyTextAltStyle)
10/5 09:21:07.811  [UI/4] [<>:0]: Unknown profile value in JSON file ($SkillHotkeyTextAltStyle)
10/5 09:21:07.815  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_L_Blank"
10/5 09:21:07.815  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_R_Blank"
10/5 09:21:07.845  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_L_Blank"
10/5 09:21:08.091  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_L_Blank"
10/5 09:21:08.126  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_L_Blank"
10/5 09:21:08.144  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_L_Blank"
10/5 09:21:08.243  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_L_Blank"
10/5 09:21:08.264  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_R_Blank"
10/5 09:21:08.281  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PauseMenu\descriptor-18"
10/5 09:21:08.283  [UI/4] [<>:0]: Unknown profile value in JSON file ($SkillHotkeyTextAltStyle)
10/5 09:21:08.327  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Docking_Bar\SidePanel_Hinge_R_Blank"
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.513  [TerrainStampComponent/4] [<>:0]: Stamp with no terrain biome
10/5 09:21:08.830  [Render/4] [<>:0]: Mesh vertex format is invalid. Filename: 'data/hd/objects/shrines_other/deer_shrine/model/fx_cloth_lod3.model', Mesh: 'deer_shrine_tarpShape'
10/5 09:21:17.836  [SpriteCache/4] [<>:0]: File not found "data/hd/global/ui/PANEL\Modals\Modal_Button"

Thanks for your time

**Comment by CollinHerber** [comment]
Unfortunately crash logs don't really give us much in D2R that is helpful.
Are you running the Latest D2R Version?

**Comment by SaijC** [comment]
ignore me just found out that the character was created in legacy mode
