### ISSUE TITLE
Investigate Flickering Flame Aura

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-mod#82]
Flame
Nef + Pul + Vex

> wildkardx: I made a flickering flame the other day and it gave me damage aura instead of lower fire res is that intended?

![image](https://github.com/user-attachments/assets/19f25a1b-db8a-4902-ae01-48b9123f40aa)

**Comment by Harald92** [comment]
Looking into it.

**Comment by Harald92** [comment]
The files represent the resist fire aura and I could not recreate the problem.
