### ISSUE TITLE
Corruption  not working on specific items

### ISSUE THREAD

**Issue by DrunknHorror** [D2R-Reimagined/d2r-reimagined-mod#83]
**Item:** Duskwreath Spiderweb sash unique    **Issue:** wont let you hit corrupt a second time to reveal  what the corruption is

**Item:**  Set items in general  multiple items of different types/slots from different sets,   it corrupted affix sometimes gets placed into the set bonus  category and not into the core part of the item.   this means the affix sometimes doesn't reveal unless you have multiple or sometimes the entire set equipped (depending on where its placed)

**Comment by Cerebral-Lag** [comment]
![image_2024-10-07_114416554](https://github.com/user-attachments/assets/e888a1bf-04f1-4f0c-bb69-ebb682e52a13)
Item corruption didn't change anything and would not let me fuse with corruption orb a second time.

**Comment by Harald92** [comment]
> Item: Duskwreath Spiderweb sash unique Issue: wont let you hit corrupt a second time to reveal what the corruption is
This is because the item did brick aka got no extra stat right?

> Item: Set items in general multiple items of different types/slots from different sets, it corrupted affix sometimes gets placed into the set bonus category and not into the core part of the item. this means the affix sometimes doesn't reveal unless you have multiple or sometimes the entire set equipped (depending on where its placed)
We have to test that, I sadly do not have a savegame with orbs atm. I would need to set that up.

@CollinHerber

**Comment by Vingelis** [comment]
Known issue with set item corruptions - we can close this issue.
